/*
 * Copyright 2023 National Bank of Belgium
 * 
 * Licensed under the EUPL, Version 1.2 or – as soon they will be approved 
 * by the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 * 
 * https://joinup.ec.europa.eu/software/page/eupl
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and 
 * limitations under the Licence.
 */
package jdplus.x11plus.desktop.plugin.x13.ui;

import jdplus.toolkit.desktop.plugin.descriptors.EnhancedPropertyDescriptor;
import jdplus.toolkit.desktop.plugin.descriptors.IPropertyDescriptors;
import jdplus.toolkit.desktop.plugin.ui.properties.l2fprod.UserInterfaceContext;
import jdplus.toolkit.base.api.timeseries.TsDomain;
import java.beans.IntrospectionException;
import java.beans.PropertyDescriptor;
import java.util.ArrayList;
import java.util.List;
import jdplus.sa.base.api.DecompositionMode;
import jdplus.toolkit.base.api.math.linearfilters.FilterSpec;
import jdplus.toolkit.base.api.math.linearfilters.HendersonSpec;
import jdplus.toolkit.base.api.math.linearfilters.LocalPolynomialFilterSpec;
import jdplus.x11plus.base.api.SeasonalFilterOption;
import jdplus.x11plus.base.api.X11plusSpec;
import org.openide.util.NbBundle;
import org.openide.util.NbBundle.Messages;

/**
 *
 * @author Jean Palate
 */
public class X11plusSpecUI implements IPropertyDescriptors {

    public enum TrendType {
        Henderson,
        LocalPolynomial
    }

    private final X13plusSpecRoot root;

    private void update(X11plusSpec nx11) {
        root.update(nx11);
    }

    private boolean isRo() {
        return root.isRo();
    }

    public X11plusSpecUI(X13plusSpecRoot root) {
        this.root = root;
    }

    public X11plusSpec spec() {
        return root.getX11();
    }

    public boolean isDefault() {
        return spec() == null;
    }

    public void setDefault(boolean def) {
        if (isDefault() == def) {
            return;
        }
        X11plusSpec spec = null;
        if (!def) {
            TsDomain domain = UserInterfaceContext.INSTANCE.getDomain();
            if (domain != null) {
                spec = X11plusSpec.createDefault(true, domain.getAnnualFrequency(), SeasonalFilterOption.S3X5);
            }
        }
        root.update(spec);
    }

    public DecompositionMode getMode() {
        return spec().getMode();
    }

    public void setMode(DecompositionMode value) {
        update(spec().toBuilder().mode(value).build());
    }

//    public boolean isUseForecast() {
//        return spec().getForecastHorizon() != 0;
//    }
    public int getForecastHorizon() {
        return spec().getForecastHorizon();
    }

    public int getBackcastHorizon() {
        return spec().getBackcastHorizon();
    }

    public boolean isSeasonal() {
        return spec().isSeasonal();
    }

    public void setSeasonal(boolean value) {
        update(spec().toBuilder().seasonal(value).build());
    }

    public void setForecastHorizon(int value) {
        update(spec().toBuilder().forecastHorizon(value).build());
    }

    public void setBackcastHorizon(int value) {
        update(spec().toBuilder().backcastHorizon(value).build());
    }

    public double getLSigma() {
        return spec().getLowerSigma();
    }

    public void setLSigma(double value) {
        update(spec().toBuilder().lowerSigma(value).build());
    }

    public double getUSigma() {
        return spec().getUpperSigma();
    }

    public void setUSigma(double value) {
        update(spec().toBuilder().upperSigma(value).build());
    }

    @Messages({
        "x11plusSpecUI.modeDesc.name=Mode",
        "x11plusSpecUI.modeDesc.desc=[mode] Decomposition mode. Could be changed by the program, if needed."
    })
    private EnhancedPropertyDescriptor modeDesc() {
        if (isDefault()) {
            return null;
        }
        try {
            PropertyDescriptor desc = new PropertyDescriptor("Mode", this.getClass());
            EnhancedPropertyDescriptor edesc = new EnhancedPropertyDescriptor(desc, MODE_ID);
            edesc.setRefreshMode(EnhancedPropertyDescriptor.Refresh.All);
            desc.setDisplayName(Bundle.x11plusSpecUI_modeDesc_name());
            desc.setShortDescription(Bundle.x11plusSpecUI_modeDesc_desc());
            edesc.setReadOnly(isRo());
            return edesc;
        } catch (IntrospectionException ex) {
            return null;
        }
    }

    @Messages({
        "x11plusSpecUI.forecastDesc.name=Forecasts horizon",
        "x11plusSpecUI.forecastDesc.desc=[forecast(maxlead)] Length of the forecasts generated by ARIMA. Negative figures are translated in years of forecasts"
    })
    private EnhancedPropertyDescriptor forecastDesc() {
        if (!root.isPreprocessing()) {
            return null;
        }
        if (isDefault()) {
            return null;
        }
        try {
            PropertyDescriptor desc = new PropertyDescriptor("ForecastHorizon", this.getClass());
            EnhancedPropertyDescriptor edesc = new EnhancedPropertyDescriptor(desc, FORECAST_ID);
            desc.setDisplayName(Bundle.x11plusSpecUI_forecastDesc_name());
            desc.setShortDescription(Bundle.x11plusSpecUI_forecastDesc_desc());
            edesc.setReadOnly(isRo());
            return edesc;
        } catch (IntrospectionException ex) {
            return null;
        }
    }

    @Messages({
        "x11plusSpecUI.backcastDesc.name=Backcasts horizon",
        "x11plusSpecUI.backcastDesc.desc=[backcast(maxback)] Length of the backcasts used in X11. Negative figures are translated in years of backcasts"
    })
    private EnhancedPropertyDescriptor backcastDesc() {
        if (!root.isPreprocessing()) {
            return null;
        }
        if (isDefault()) {
            return null;
        }
        try {
            PropertyDescriptor desc = new PropertyDescriptor("BackcastHorizon", this.getClass());
            EnhancedPropertyDescriptor edesc = new EnhancedPropertyDescriptor(desc, BACKCAST_ID);
            desc.setDisplayName(Bundle.x11plusSpecUI_backcastDesc_name());
            desc.setShortDescription(Bundle.x11plusSpecUI_backcastDesc_desc());
            edesc.setReadOnly(isRo());
            return edesc;
        } catch (IntrospectionException ex) {
            return null;
        }
    }

    @Messages({
        "x11plusSpecUI.lsigmaDesc.name=LSigma",
        "x11plusSpecUI.lsigmaDesc.desc=[sigmalim] Lower sigma boundary for the detection of extreme values."
    })
    private EnhancedPropertyDescriptor lsigmaDesc() {
        if (isDefault()) {
            return null;
        }
        try {
            PropertyDescriptor desc = new PropertyDescriptor("LSigma", this.getClass());
            EnhancedPropertyDescriptor edesc = new EnhancedPropertyDescriptor(desc, LSIGMA_ID);
            edesc.setRefreshMode(EnhancedPropertyDescriptor.Refresh.All);
            desc.setDisplayName(Bundle.x11plusSpecUI_lsigmaDesc_name());
            desc.setShortDescription(Bundle.x11plusSpecUI_lsigmaDesc_desc());
            edesc.setReadOnly(isRo());
            return edesc;
        } catch (IntrospectionException ex) {
            return null;
        }
    }

    @Messages({
        "x11plusSpecUI.usigmaDesc.name=USigma",
        "x11plusSpecUI.usigmaDesc.desc=[sigmalim] Upper sigma boundary for the detection of extreme values."
    })
    private EnhancedPropertyDescriptor usigmaDesc() {
        if (isDefault()) {
            return null;
        }
        try {
            PropertyDescriptor desc = new PropertyDescriptor("USigma", this.getClass());
            EnhancedPropertyDescriptor edesc = new EnhancedPropertyDescriptor(desc, USIGMA_ID);
            edesc.setRefreshMode(EnhancedPropertyDescriptor.Refresh.All);
            desc.setDisplayName(Bundle.x11plusSpecUI_usigmaDesc_name());
            desc.setShortDescription(Bundle.x11plusSpecUI_usigmaDesc_desc());
            edesc.setReadOnly(isRo());
            return edesc;
        } catch (IntrospectionException ex) {
            return null;
        }
    }

    public TrendType getTrendType() {
        FilterSpec tspec = spec().getTrendFilter();
        if (tspec instanceof LocalPolynomialFilterSpec) {
            return TrendType.LocalPolynomial;
        } else if (tspec instanceof HendersonSpec) {
            return TrendType.Henderson;
        } else {
            return null;
        }
    }

    public IPropertyDescriptors getTrendFilter() {
        FilterSpec tspec = spec().getTrendFilter();
        if (tspec instanceof LocalPolynomialFilterSpec lpspec) {
            return new LocalPolynomialSpecUI(lpspec, isRo(), nspec
                    -> {
                update(spec().toBuilder()
                        .trendFilter(nspec)
                        .build());
            }
            );
        } else if (tspec instanceof HendersonSpec) {
            return new HendersonSpecUI(root);
        } else {
            return null;
        }
    }

    public void setTrendType(TrendType type) {
        FilterSpec nspec = null;
        TsDomain domain = UserInterfaceContext.INSTANCE.getDomain();
        if (domain == null) {
            return;
        }
        switch (type) {
            case Henderson ->
                nspec = new HendersonSpec(domain.getAnnualFrequency(), 3.5);
            case LocalPolynomial ->
                nspec = LocalPolynomialFilterSpec.DEF_TREND_SPEC
                        .toBuilder()
                        .filterHorizon(domain.getAnnualFrequency() / 2)
                        .build();
        }
        if (nspec != null) {
            update(spec().toBuilder()
                    .trendFilter(nspec)
                    .build());
        }
    }

    @Override
    public List<EnhancedPropertyDescriptor> getProperties() {
        ArrayList<EnhancedPropertyDescriptor> descs = new ArrayList<>();
        EnhancedPropertyDescriptor desc = defDesc();
        if (desc != null) {
            descs.add(desc);
        }
        desc = modeDesc();
        if (desc != null) {
            descs.add(desc);
        }
        desc = seasDesc();
        if (desc != null) {
            descs.add(desc);
        }
        desc = forecastDesc();
        if (desc != null) {
            descs.add(desc);
        }
        desc = backcastDesc();
        if (desc != null) {
            descs.add(desc);
        }
        desc = lsigmaDesc();
        if (desc != null) {
            descs.add(desc);
        }
        desc = usigmaDesc();
        if (desc != null) {
            descs.add(desc);
        }
        desc = iseasDesc();
        if (desc != null) {
            descs.add(desc);
        }
        desc = fseasDesc();
        if (desc != null) {
            descs.add(desc);
        }
        desc = trendDesc();
        if (desc != null) {
            descs.add(desc);
        }
        desc = trendTypeDesc();
        if (desc != null) {
            descs.add(desc);
        }
        return descs;
    }
//    ///////////////////////////////////////////////////////////////////////////
    private static final int DEF_ID = -1, MODE_ID = 0, SEAS_ID = 1, FORECAST_ID = 2, BACKCAST_ID = 12, LSIGMA_ID = 3, USIGMA_ID = 4, AUTOTREND_ID = 5,
            TREND_ID = 6, ISEAS_ID = 7, FSEAS_ID = 8, TRENDTYPE_ID=10;

    @NbBundle.Messages({
        "x11plusSpecUI.defDesc.name=Default",
        "x11plusSpecUI.defDesc.desc=Is Default?"
    })
    private EnhancedPropertyDescriptor defDesc() {
        try {
            PropertyDescriptor desc = new PropertyDescriptor("Default", this.getClass());
            EnhancedPropertyDescriptor edesc = new EnhancedPropertyDescriptor(desc, TREND_ID);
            desc.setDisplayName(Bundle.x11plusSpecUI_defDesc_name());
            desc.setShortDescription(Bundle.x11plusSpecUI_defDesc_desc());
            return edesc;
        } catch (IntrospectionException ex) {
            return null;
        }
    }

    @NbBundle.Messages({
        "x11plusSpecUI.trendDesc.name=TREND",
        "x11plusSpecUI.trendDesc.desc=Trend specification."
    })
    private EnhancedPropertyDescriptor trendDesc() {
        if (isDefault()) {
            return null;
        }
        try {
            PropertyDescriptor desc = new PropertyDescriptor("TrendFilter", this.getClass(), "getTrendFilter", null);
            EnhancedPropertyDescriptor edesc = new EnhancedPropertyDescriptor(desc, TREND_ID);
            desc.setDisplayName(Bundle.x11plusSpecUI_trendDesc_name());
            desc.setShortDescription(Bundle.x11plusSpecUI_trendDesc_desc());
            return edesc;
        } catch (IntrospectionException ex) {
            return null;
        }
    }

    @NbBundle.Messages({
        "x11plusSpecUI.trendTypeDesc.name=Trend type",
        "x11plusSpecUI.trendTypeDesc.desc=Trend specification."
    })
    private EnhancedPropertyDescriptor trendTypeDesc() {
        if (isDefault()) {
            return null;
        }
        try {
            PropertyDescriptor desc = new PropertyDescriptor("TrendType", this.getClass());
            EnhancedPropertyDescriptor edesc = new EnhancedPropertyDescriptor(desc, TRENDTYPE_ID);
            desc.setDisplayName(Bundle.x11plusSpecUI_trendTypeDesc_name());
            desc.setShortDescription(Bundle.x11plusSpecUI_trendTypeDesc_desc());
            return edesc;
        } catch (IntrospectionException ex) {
            return null;
        }
    }

    @NbBundle.Messages({
        "x11plusSpecUI.iseasDesc.name=Initial seasonal filter",
        "x11plusSpecUI.iseasDesc.desc=Initial seasonal filter"
    })
    private EnhancedPropertyDescriptor iseasDesc() {
        if (isDefault()) {
            return null;
        }
        try {
            PropertyDescriptor desc = new PropertyDescriptor("SeasonalFilter", this.getClass(), "getInitialSeasonalFilter", null);
            EnhancedPropertyDescriptor edesc = new EnhancedPropertyDescriptor(desc, ISEAS_ID);
            desc.setDisplayName(Bundle.x11plusSpecUI_iseasDesc_name());
            desc.setShortDescription(Bundle.x11plusSpecUI_iseasDesc_desc());
            return edesc;
        } catch (IntrospectionException ex) {
            return null;
        }
    }

    @NbBundle.Messages({
        "x11plusSpecUI.fseasDesc.name=Final seasonal filter",
        "x11plusSpecUI.fseasDesc.desc=Final seasonal filter"
    })
    private EnhancedPropertyDescriptor fseasDesc() {
        if (isDefault()) {
            return null;
        }
        try {
            PropertyDescriptor desc = new PropertyDescriptor("SeasonalFilter", this.getClass(), "getFinalSeasonalFilter", null);
            EnhancedPropertyDescriptor edesc = new EnhancedPropertyDescriptor(desc, FSEAS_ID);
            desc.setDisplayName(Bundle.x11plusSpecUI_fseasDesc_name());
            desc.setShortDescription(Bundle.x11plusSpecUI_fseasDesc_desc());
            return edesc;
        } catch (IntrospectionException ex) {
            return null;
        }
    }

    @NbBundle.Messages({
        "x11plusSpecUI.seasDesc.name=Initial seasonal filter",
        "x11plusSpecUI.seasDesc.desc=Initial seasonal filter"
    })
    private EnhancedPropertyDescriptor seasDesc() {
        if (isDefault()) {
            return null;
        }
        try {
            PropertyDescriptor desc = new PropertyDescriptor("SeasonalFilter", this.getClass(), "getInitialSeasonalFilter", null);
            EnhancedPropertyDescriptor edesc = new EnhancedPropertyDescriptor(desc, ISEAS_ID);
            desc.setDisplayName(Bundle.x11plusSpecUI_seasDesc_name());
            desc.setShortDescription(Bundle.x11plusSpecUI_seasDesc_desc());
            return edesc;
        } catch (IntrospectionException ex) {
            return null;
        }
    }

    @Messages("x11plusSpecUI.getDisplayName=X11+")
    @Override
    public String getDisplayName() {
        return Bundle.x11plusSpecUI_getDisplayName();
    }

}
